title: Daniel Doubrovkine | Tech Blog
email: dblock@dblock.org
baseurl: ""
url: "http://code2.dblock.org"
twitter_username: dblockdotorg
github_username:  dblock
markdown: kramdown
kramdown:
  input: GFM
gems:
  - jekyll-redirect-from

