title: code.dblock.org | tech blog
locale: en_US
url:
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-archives
kramdown:
  input: GFM
owner:
  name: Daniel Doubrovkine
  avatar: blog.gif
  bio: "aka dB., Head of Engineering at <a href='https://artsy.net' target='_blank'>artsy.net</a> in New York City, open-source cheerleader"
  email: dblock@dblock.org
  disqus-shortname: dblockdotorg
  twitter: dblockdotorg
  facebook:
  google:
    plus:
    analytics: UA-4756101-3
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: dblock
  stackoverflow:
  linkedin: dblock
  instagram:
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  youtube:
  soundcloud:
paginate: 30
google_custom_search: "015938957525977311805:c-2lieekft8"
jekyll-archives:
  enabled:
    - tags
  layout: 'archive'
  permalinks:
    tag: '/tag/:name/'
