title: code.dblock.org | tech blog
locale: en_US
url:
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
kramdown:
  input: GFM
owner:
  name: Daniel Doubrovkine
  avatar: blog.gif
  bio: "Daniel Doubrovkine (aka dB.) is Head of Engineering at Artsy in New York and an open-source cheerleader."
  email: dblock@dblock.org
  disqus-shortname: dblockdotorg
  twitter: dblockdotorg
  facebook:
  google:
    plus:
    analytics: UA-4756101-3
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: dblock
  stackoverflow:
  linkedin: dblock
  instagram:
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  youtube:
  soundcloud:
paginate: 30
