name: link-checker

on:
  repository_dispatch:
  workflow_dispatch:
  # push:
  # schedule:
  #   - cron: "00 18 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: https://code.dblock.org --verbose

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue